name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.26'

      - name: Cache modules
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install modules
        run: |
          go mod download

      - run: mkdir -p /tmp/test-results

      - name: Run Tests
        run: |
          go tool gotestsum --junitfile /tmp/test-results/unit-tests.xml -- ./... -coverprofile=/tmp/test-coverage.txt

      - name: Upload Code Coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: /tmp/test-coverage.txt
          fail_ci_if_error: true
          verbose: true
  tag:
    name: "Tag Version"
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.set-outputs.outputs.branch }}
      tag: ${{ steps.bump_version.outputs.tag }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: "0"
          fetch-tags: true

      - name: Bump version and push tag
        if: ${{ github.ref == 'refs/heads/main' }}
        id: bump_version
        uses: ministryofjustice/opg-github-actions/actions/semver@939ca6ddfc2bafefa48b0730ea0268bd75a25876 # v4.9.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          create_release: false
          default_bump: minor
          without_prefix: false        
